Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FinalProject.Models;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Configuration;
using System.Data;
using System.Web;

namespace FinalProject.Controllers
{
    public class EnrollmentController : Controller

    {
        public string value = "";
        // GET: EnrollmentController
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Enroll e)
        {
           
            
                Enroll er = new Enroll();
                using (SqlConnection con = new SqlConnection("Data Source=(localdb)\\ProjectModels;Initial Catalog=FinalProject;Integrated Security=True;"))
                {
                    using (SqlCommand cmd = new SqlCommand("EnrollDetail", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@LoginName", e.LoginName);
                        cmd.Parameters.AddWithValue("@FullName", e.FullName);
                        cmd.Parameters.AddWithValue("@Password", e.Password);
                    cmd.Parameters.AddWithValue("@ConfirmPassword", e.ConfirmPassword);
                    cmd.Parameters.AddWithValue("@Gender", e.Gender);
                        cmd.Parameters.AddWithValue("@EmailId", e.EmailId);
                        cmd.Parameters.AddWithValue("@PhoneNumber", e.PhoneNumber);
                   
                       // cmd.Parameters.AddWithValue("@status", "INSERT");
                        con.Open();
                        ViewData["result"] = cmd.ExecuteNonQuery();
                        con.Close();
                    
                }
            }
            return View();
        }




        // GET: EnrollmentController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EnrollmentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EnrollmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EnrollmentController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EnrollmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EnrollmentController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EnrollmentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/UserController.cs
using FinalProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;

namespace FinalProject.Controllers
{
    public class UserController : Controller
    {
        db dbop = new db();
        // GET: UserController
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Enroll e)
        {
            Enroll er = new Enroll();
            using (SqlConnection con = new SqlConnection("Data Source=(localdb)\\ProjectModels;Initial Catalog=FinalProject;Integrated Security=True;"))
            {
                using (SqlCommand cmd = new SqlCommand("EnrollDetail", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@LoginName", e.LoginName);
                    cmd.Parameters.AddWithValue("@FullName", e.FullName);
                    cmd.Parameters.AddWithValue("@Password", e.Password);
                    cmd.Parameters.AddWithValue("@ConfirmPassword", e.ConfirmPassword);
                    cmd.Parameters.AddWithValue("@Gender", e.Gender);
                    cmd.Parameters.AddWithValue("@EmailId", e.EmailId);
                    cmd.Parameters.AddWithValue("@PhoneNumber", e.PhoneNumber);

                    // cmd.Parameters.AddWithValue("@status", "INSERT");
                    con.Open();
                    ViewData["result"] = cmd.ExecuteNonQuery();
                    con.Close();

                }
            }


            return View();
        }


        // GET: UserController/Details/5
        public ActionResult Details([Bind] ULogin ul)
        {
            try
            {
                db dbop = new db();
                int res = dbop.LoginCheck(ul);
                if (res == 1)
                {
                    TempData["msg"] = "Welcome User..!!";
                    return View("Create");
                }
                else
                {
                    TempData["msg"] = "Login Name or Password is wrong.!";
                }




                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Complain c)
        {
            try
            {
                Enroll er = new Enroll();
                using (SqlConnection con = new SqlConnection("Data Source=(localdb)\\ProjectModels;Initial Catalog=FinalProject;Integrated Security=True;"))
                {
                    using (SqlCommand cmd = new SqlCommand("EnrollComplain", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@Id", c.Id);
                        cmd.Parameters.AddWithValue("@Category", c.Category);
                        cmd.Parameters.AddWithValue("@Description", c.Description);
                        cmd.Parameters.AddWithValue("@Status", c.Status);


                        // cmd.Parameters.AddWithValue("@status", "INSERT");
                        con.Open();
                        ViewData["result"] = cmd.ExecuteNonQuery();
                        con.Close();

                    }
                }


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/User/Create.cshtml

   @model FinalProject.Models.Complain
    @{
        ViewData["Title"] = "";
    }
    <h1>@ViewData["Title"]</h1>

    <h1>Please Add Your Complain</h1>
    <!DOCTYPE html>
    <html>
    <head>

    </head>
    <body>
        <form class="form-horizontal" asp-action="Create">

            <div class="form-group">
                @Html.TextBoxFor(e => e.Id, new { @class = "form-control", placeholder = "Id*" })
                @Html.ValidationMessageFor(e => e.Id)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(e => e.Category, new { @class = "form-control", placeholder = "Category*" })
                @Html.ValidationMessageFor(e => e.Category)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(e => e.Description, new { @class = "form-control", placeholder = "Description*" })
                @Html.ValidationMessageFor(e => e.Description)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(e => e.Status, new { @class = "form-control", placeholder = "Status*" })
                @Html.ValidationMessageFor(e => e.Status)
            </div>
            <div>
                <input type="submit" class="btnRegister" value="Submit" />
            </div>
        </form>
    </body>
</html>




Views/User/Details.cshtml
@model FinalProject.Models.ULogin
@{
    ViewData["Title"] = "";
}

<div class="container">
    <h1>Login Page</h1>
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <form class="form-horizontal" asp-action="Details">
                <div class="form-group">
                    <label class="control-label">Login Name</label>
                    <input asp-for="LoginName" class="form-control" type="text" />
                </div>
                <div class="form-group">
                    <label class="control-label">Password</label>
                    <input asp-for="Password" class="form-control" type="password" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Submit" />
                </div>
            </form>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>
@{
    if (TempData["msg"] != null)
    {
        <script>
            alert('@TempData["msg"]')
        </script>
    }
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


Views/User/Index.cshtml

@model FinalProject.Models.Enroll
@{
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ENROLLMENT</title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
    <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="../../Content/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="~/Scripts/jquery-1.7.1.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/Scripts/passwordscheck.js"></script>
    <link href="~/Scripts/passwordscheck.css" rel="stylesheet" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
</head>
<body>
    <!------ Include the above in your HEAD tag ---------->
    @using (Html.BeginForm("Index", "Enrollment", FormMethod.Post))
    {
        <div class="container register">
            <div class="row">
                <div class="col-md-3 register-left">
                    <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt="" />
                    <h3>Welcome User</h3>
                   
                </div>
                <div class="col-md-9 register-right">
                    <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="../User/Index" role="tab" aria-controls="home" aria-selected="true">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="../User/Details" role="tab" aria-controls="profile" aria-selected="false">Login</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <h3 class="register-heading">Register</h3>
                            <div class="row register-form">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.LoginName, new { @class = "form-control", placeholder = "Login Name *" })
                                        @Html.ValidationMessageFor(e => e.LoginName)
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.FullName, new { @class = "form-control", placeholder = "Full Name *" })
                                        @Html.ValidationMessageFor(e => e.FullName)
                                    </div>
                                    <div class="form-group">
                                        @Html.PasswordFor(e => e.Password, new { id = "password", @class = "form-control", placeholder = "Password *" })
                                        <span id="result"></span>
                                        @Html.ValidationMessageFor(e => e.Password)
                                    </div>
                                    <div class="form-group">
                                        @Html.PasswordFor(e => e.ConfirmPassword, new { @class = "form-control", placeholder = "Confirm Password *" })
                                        @Html.ValidationMessageFor(e => e.ConfirmPassword)
                                    </div>
                                    <div class="form-group">
                                        <div class="maxl">
                                            @Html.RadioButtonFor(e => e.Gender, "Male", new { @class = "radio inline" })<span> Male </span>
                                            @Html.RadioButtonFor(e => e.Gender, "Female", new { @class = "radio inline" })<span>Female </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.EmailId, new { @class = "form-control", placeholder = "Your Email *" })
                                        @Html.ValidationMessageFor(e => e.EmailId)
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.PhoneNumber, new { @class = "form-control", placeholder = "Your Phone *" })
                                        @Html.ValidationMessageFor(e => e.PhoneNumber)

                                    </div>
                                   
                                   
                                    <input type="submit" class="btnRegister" value="Register" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script type="text/javascript">

                $(function () {
                   var msg = '@ViewData["result"]';
                   if (msg == '1')
                   {
                       alert("User Details Inserted Successfully");
                       window.location.href = "@Url.Action("Index", "Enrollment")";
                    }
                   });
            </script>
            }
        </div>
    }
</body>
</html>

